package com.fpltn.entities;
// Generated 16:00:59, 13 thg 4, 2023 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Danhmuc generated by hbm2java
 */
@Entity
@Table(name = "danhmuc", catalog = "dbweb")
public class Danhmuc implements java.io.Serializable {

	private Integer id;
	private String tendm;
	private String mota;

	public Danhmuc() {
	}

	public Danhmuc(String tendm) {
		this.tendm = tendm;
	}

	public Danhmuc(String tendm, String mota) {
		this.tendm = tendm;
		this.mota = mota;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tendm", nullable = false, length = 45)
	public String getTendm() {
		return this.tendm;
	}

	public void setTendm(String tendm) {
		this.tendm = tendm;
	}

	@Column(name = "mota", length = 150)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

}
